server:
    port: 8080

# Reduce logging level. Set logging level to warn
logging:
    level:
        root: warn
        org:
            hibernate:
                SQL: debug
                orm:
                    jdbc:
                        bind: trace

spring:
    application:
        name: accounts
    main:
        banner-mode: off
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: ''
    h2:
        console:
            enabled: true
        
build:
    version: "1.0"            

accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345